### ISSUE TITLE
inconsistent use of nshares and num_shares

### ISSUE THREAD

**Issue by R-K-H** [MiniXC/simple-back#21] opened 2020-06-29 15:35 UTC
https://github.com/MiniXC/simple-back/blob/master/simple_back/backtester.py#L1312
https://github.com/MiniXC/simple-back/blob/master/simple_back/backtester.py#L137

So a position has `num_shares` but when opening a position you have `nshares`

I fought with this last night for quite a while just based on expectation that it would have been consistent across the implementation, not sure if this is by design or just different period of development, but it would seem they should be one in the same?

Just a small nag, and open for discussion.

**Comment by MiniXC** [comment] 2020-06-30 07:12
This is not by design but results from an evolving code base. Easy to fix though, so expect it to be gone soon.

**Comment by MiniXC** [comment] 2020-06-30 13:00
fixed in 2dc28d7c17a0d2de5d5739a16b9dede7e42d5858, thanks for reporting

**Closed by MiniXC** 2020-06-30 13:00 UTC
